config/routes.rb
Rails.application.routes.draw do

  #root 'categories#index'
          # root :controller => 'static', :action => '/' 
          # above does same as below.
          root :controller => 'static', :action => '/public/index.html'
#  root 'categories#retester'
  resources :categories do
    resources :items
  end

  resources :cart do
      resources :items
  end
    # get 'cart_tmpl', to:'cart#cart_tmpl'
    # delete 'item_storage' to:'shopping_cart#'   
  
  post 'cart_tmpl', to:'cart#cart_tmpl'
  

  resources :users
  delete 'sessions', to:'sessions#destroy'
  get 'sessions/new', to:'sessions#new'
  post 'sessions/new', to:'sessions#create'
  get 'test/email', to:'categories#email_test'
  # get 'shopping_cart/add_item', to:'shopping_cart#add_item'


  # resources :sessions, only: [:new, :destroy, :create]


end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true
  validates :name, uniqueness: true
  has_many :items, as: :itemable
end

app/controllers/categories_controller.rb
class Viewfiller
    attr_accessor :name, :id
  def initialize(*args)
    @name = args[0] || 'Coming Soon'
    @id = args[1] || 234  
  end


end
class CategoriesController < ApplicationController
 include AdminHelper
  def index
    # @categories = Array.new(cats.length%3, {})
    # cats.each do |cat|
    #   @categories << cat
    # end
     @categories = Category.all
      @categories.length%4.times do 
          @categories << Viewfiller.new
      end
      @categories
  end

  def show
    @category = Category.find_by(id: params[:id])  
    @category    

  end

  def create
     category =  Category.new(category_params)
      if category.save
        redirect_to categories_path
      else
        redirect_to new_category_path
      end
  end

  def destroy
    @category = Category.find_by(id: params[:id])
    @category.destroy
    redirect_to categories_path
  end

  def update

  end

  def edit
    @category = Category.find(params[:category_id])
    @item = Item.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def email_test
    user = User.find_by(email: 'shaneenterprises@gmail.com')
     UserMailer.welcome_email(user).deliver_now
      redirect_to root_path
  end
    private
  def category_params
    params.require(:category).permit(:name)
  end

end

app/views/categories/`show.bak.html.haml
-if is_admin?
  = button_to('Add Item',new_category_item_path(@category.id),{:class => 'btn btn-default', :method => 'get'})
%table.table-hover.table-responsive{:style => "width:100%"}
  %tr
    %th.title.col-md-2
    %th.title.col-md-2
      %h3 Title
    %th.title.col-md-2
      %h3 Stock
    %th.title.col-md-2
      %h3 Price
    %th.title.col-md-2
  %tr
    - @category.items.each do |product|
      %tr
        %td
          %a{ href: category_item_path(@category, product) }
            %img{ :src => product.image_url, :width => "300"}
        %td
          %h4.title
            %a{ href: category_item_path(@category, product) }
              = product.name
        %td
          %h4.title
            = product.quantity
        %td
          %h4.title
            = product.price
        %td
          =link_to 'Add To Cart', '#', :onclick => 'addItemToCart(this)', :item_id => product.id            
      - if is_admin?
        %td
          = button_to 'Edit', edit_category_item_path(@category.id, product.id),{:method => :get, :class => 'btn btn-danger edit-button'}
          = button_to 'Delete', category_item_path(@category.id, product.id),{:method =>:delete, :data => { :confirm => 'Are you sure?' }, :class => "btn btn-danger delete-button"}

app/views/categories/index.html.haml
.jumbotron.jumbotron-fluid
  .container
    %h1.display-3 Chris Commerce
    %p.lead  The way online shopping will be.
    - if is_admin?  
      %span.nav-item.dropdown.pull-right
        %a.dropdown-toggle.text-info{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"} Admin Controls
        .dropdown-menu
          %a.dropdown-item{:href => "#"} Action
          %a.dropdown-item{:href => "#"} Another action
          %a.dropdown-item{:href => "#"} Something else here
          .dropdown-divider
          = link_to('Send Email',test_email_path, {:class => "dropdown-item"})        
          = link_to('Create Category',new_category_path, {:class => "text-success dropdown-item"})          
.row
  - @categories.each do |cat|
    .col-xs-8.col-xs-offset-2.col-sm-4.col-sm-offset-0
      %figure.figure.text-center
        %a{:href => category_path(cat.id)} 
          = image_tag("holder.jpg", style: "width:100%; height:100%", alt: "Edit Entry")
        %h1.display-4.category-name
          = cat.name.length > 10 ? cat.name.slice!(0, 10).insert(-1,'..') : cat.name

app/views/categories/new.html.haml
%h1 Create a New Category!
= form_for @category, :html => {:class => " form-horizontal"} do |f|
  %fieldset.form-group
    = f.label :name_of_category, class: "col-md-4 control-label"
    .col-md-6
      = f.text_field :name, class: "form-control"
  .color
  = f.submit

app/views/categories/show.html.haml
.jumbotron.jumbotron-fluid
  .container
    %h1.display-3 
      = @category.name
    %p.lead
    - if is_admin?  
      %span.nav-item.dropdown.pull-right
        %a.dropdown-toggle.text-info{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"} Admin Controls
        .dropdown-menu
          %a.dropdown-item{:href => "#"} Action
          %a.dropdown-item{:href => "#"} Another action
          %a.dropdown-item{:href => "#"} Something else here
          .dropdown-divider
          = link_to('Send Email',test_email_path, {:class => "dropdown-item"})
          = link_to('Add Item', new_category_item_path(@category.id), {:class => 'text-success dropdown-item'})
.row
  - @category.items.each do |x|
    .col-xs-8.col-xs-offset-2.col-sm-4.col-sm-offset-0
      %figure.figure.text-center
        %a{:href => category_item_path(@category.id, x.id)} 
          = image_tag("holder.jpg", style: "width:100%; height:100%", alt: "Edit Entry")
        %h1.display-4.category-name
          = x.name.length > 10 ? x.name.slice!(0, 10).insert(-1,'..') : x.name