config/routes.rb
Rails.application.routes.draw do

  #root 'categories#index'
          # root :controller => 'static', :action => '/' 
          # above does same as below.
          root :controller => 'static', :action => '/public/index.html'
#  root 'categories#retester'
  resources :categories do
    resources :items
  end

  resources :cart do
      resources :items
  end
    # get 'cart_tmpl', to:'cart#cart_tmpl'
    # delete 'item_storage' to:'shopping_cart#'   
  
  post 'cart_tmpl', to:'cart#cart_tmpl'
  

  resources :users
  delete 'sessions', to:'sessions#destroy'
  get 'sessions/new', to:'sessions#new'
  post 'sessions/new', to:'sessions#create'
  get 'test/email', to:'categories#email_test'
  # get 'shopping_cart/add_item', to:'shopping_cart#add_item'


  # resources :sessions, only: [:new, :destroy, :create]


end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Shoppe
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application', debug: true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-dark.bg-inverse
      %button.navbar-toggler.hidden-sm-up{"data-target" => "#exCollapsingNavbar2", "data-toggle" => "collapse", :type => "button"}
        ☰
      #exCollapsingNavbar2.collapse.navbar-toggleable-xs
        %a.navbar-brand{:href => "#"}
          %span.fa.fa-chevron-left
          %span.fa.fa-chevron-left
        %ul.nav.navbar-nav.pull-left
          %li.nav-item.dropdown
            = link_to 'Go!', '#', {:class => "dropdown-toggle nav-link text-info", "aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :role => "button"} 
            .dropdown-menu
              %a.dropdown-item{:href => "#"} Action
              %a.dropdown-item{:href => "#"} Another action
              %a.dropdown-item{:href => "#"} Something else here
              .dropdown-divider
              %a.dropdown-item{:href => "#"} Separated link





        %ul.nav.navbar-nav.pull-right
          %li.nav-item.active
            = link_to raw(home_glyph), root_path, :class =>  'nav-link'
          - if current_user
            %li.nav-item
              %a.nav-link{:href => "/users/#{current_user.id}"}
                %span.glyphicon.glyphicon-user{"aria-hidden" => "true"}
            %li.nav-item
              = link_to raw(user_glyph), user_path(current_user.id), {:class => 'nav-link'}                
            %li.nav-item
              = link_to raw(shopping_cart_glyph), '#',{:id => 'cart_modal_btn', :class => 'nav-link'} 
            %li.nav-item
              = link_to raw(sign_out_glyph), sessions_path, {method: :delete, :class => 'nav-link'}
          - else
            %li.nav-item
              %a.nav-link.text-success{:href => "/users/new"} SignUp!
            %li.nav-item
              = link_to raw(sign_in_glyph), sessions_new_path, {:class => 'nav-link'}
          / if there is a session id then display user info
      / /.navbar-collapse
  .container 
    =yield

app/views/layouts/~navbar.html.haml
    %nav.navbar.navbar-dark.bg-inverse    
      .navbar-header
        %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand.txt-uppercase{:href => "/"} 
          - if current_user
            = current_user.first_name
          - else
            Guest
      #navbar.navbar-collapse.collapse
        %ul.nav.navbar-nav
          %li.active
            %a{:href => "/"} Home
          %li
            %a{:href => "/secret"} Secret Area
          - if is_admin?  
            %li.dropdown
              %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                Admin Controls
                %span 
              %ul.dropdown-menu
                %li
                  = link_to('Send Email',test_email_path)
                %li
                  %a{:href => "#"} Reports
                %li
                %li.divider{:role => "separator"}
                %li.dropdown-header Categories
                %li
                  = link_to('Category List', root_path)
                %li
                  = link_to('Create New Category', new_category_path)
          / If user logged in and there is a session id then show below
          - if session[:user_id]
            %li
              = link_to 'Logout', sessions_path, method: :delete, class: 'btn btn-group'
            %li
              %a{ :id => 'cart_modal_btn'}
                Cart
          - else
            %li
              %a{:href => "/users/new"} Register
            %li
              %a{:href => "/sessions/new" } Login
          / if there is a session id then display user info
          - if current_user
            %li
              %a{:href => "/users/#{current_user.id}"}
                %span.glyphicon.glyphicon-user{"aria-hidden" => "true"}
      / /.navbar-collapse